# Generated by Django 5.1 on 2026-05-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('is_in_use', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, help_text="Optional label e.g. 'Link 1', 'Backup link'", max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_in_use', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_enabled', models.BooleanField(default=True, help_text='Uncheck to disable all new bookings')),
                ('service_off_message', models.TextField(blank=True, default='Our service is temporarily unavailable. Please check back soon.', help_text='Shown on homepage when booking is disabled')),
                ('service_off_from', models.DateField(blank=True, help_text='Optional: start date of downtime shown to users', null=True)),
                ('service_off_until', models.DateField(blank=True, help_text='Optional: end date of downtime shown to users', null=True)),
                ('slot_duration_minutes', models.PositiveIntegerField(default=15, help_text='Duration of each consultation slot in minutes')),
                ('booking_fee', models.PositiveIntegerField(default=50, help_text='Upfront booking fee in BDT')),
                ('cancellation_deduction', models.PositiveIntegerField(default=10, help_text='Amount deducted from refund on cancellation in BDT')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
