# Generated by Django 5.1 on 2026-05-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bkash_merchant_number',
            field=models.CharField(blank=True, default='', help_text='Your bKash merchant/personal number shown to users for payment', max_length=20),
        ),
    ]
