# Generated by Django 5.1 on 2026-06-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_bkash_merchant_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sitewide_discount_enabled',
            field=models.BooleanField(default=False, help_text='Enable a sitewide discount on all consultation fees'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sitewide_discount_label',
            field=models.CharField(blank=True, default='', help_text="Shown to users e.g. 'Eid Special — 15% off all consultations'", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sitewide_discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sitewide_discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage (e.g. 20 for 20%) or fixed amount in Taka', max_digits=8),
        ),
    ]
