# Generated by Django 5.1 on 2026-06-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_sitewide_discount_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sitewide_discount_expiry',
            field=models.DateField(blank=True, help_text='Optional — discount automatically deactivates after this date', null=True),
        ),
    ]
