# Generated by Django 5.1 on 2026-06-07 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_sitewide_discount_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('payment_verified', 'Payment Verified'), ('payment_failed', 'Payment Marked Failed'), ('payment_refunded', 'Payment Refunded'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('vet_approved', 'Vet Application Approved'), ('vet_rejected', 'Vet Application Rejected'), ('settings_changed', 'Site Settings Changed'), ('coupon_created', 'Coupon Created'), ('coupon_toggled', 'Coupon Toggled'), ('coupon_deleted', 'Coupon Deleted'), ('appt_cancelled', 'Appointment Cancelled by Admin')], max_length=50)),
                ('description', models.TextField()),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
