# Generated by Django 5.1 on 2026-06-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_verification_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, new users must verify their email before booking.'),
        ),
    ]
