# Generated by Django 5.1 on 2026-06-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_created_at_user_is_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True, help_text="False only when email verification is enabled and user hasn't verified yet."),
        ),
    ]
