# Generated by Django 5.1 on 2026-05-14 21:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_address_user_created_at_user_is_banned_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Booking Payment'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('in_progress', 'In Progress'), ('awaiting_second_payment', 'Awaiting Consultation Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=30)),
                ('primary_complaint', models.CharField(choices=[('digestive', 'Digestive Issue'), ('skin', 'Skin / Fur Problem'), ('behavioural', 'Behavioural Issue'), ('injury', 'Injury'), ('breathing', 'Breathing Problem'), ('eating', 'Not Eating / Loss of Appetite'), ('vaccination', 'Vaccination Advice'), ('general', 'General Checkup'), ('other', 'Other')], max_length=20)),
                ('complaint_description', models.TextField(help_text='User describes the issue in their own words')),
                ('symptom_photo', models.ImageField(blank=True, null=True, upload_to='symptom_photos/')),
                ('consultation_start_time', models.DateTimeField(blank=True, help_text='Set when vet clicks Start Meeting', null=True)),
                ('consultation_end_time', models.DateTimeField(blank=True, help_text='Set when vet clicks End Meeting', null=True)),
                ('consultation_notes', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('reschedule_count', models.PositiveIntegerField(default=0)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('feedback_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_comment', models.TextField(blank=True)),
                ('feedback_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meet_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.meetlink')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='consultations.appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.vetprofile')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('booking', 'Booking Fee'), ('consultation', 'Consultation Fee')], max_length=15)),
                ('amount', models.PositiveIntegerField(help_text='Amount in BDT')),
                ('bkash_number', models.CharField(help_text="User's bKash number used to send payment", max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('wrong_transaction', 'Wrong Transaction ID'), ('failed', 'Failed / Discarded'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.PositiveIntegerField(blank=True, help_text='Amount to refund after deduction', null=True)),
                ('refund_sent_at', models.DateTimeField(blank=True, null=True)),
                ('refund_bkash_number', models.CharField(blank=True, help_text='bKash number to send refund to', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='consultations.appointment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('other', 'Other')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('age_years', models.PositiveIntegerField(default=0)),
                ('age_months', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('medical_history_notes', models.TextField(blank=True, help_text="Ongoing notes about this pet's health history. Vets can add to this.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='consultations.pet'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications', models.TextField(help_text='List medications, one per line')),
                ('dosage_instructions', models.TextField(help_text='Dosage and administration instructions')),
                ('follow_up_advice', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Auto-generated PDF — do not upload manually', null=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='consultations.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='VetAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recurring', models.BooleanField(default=True, help_text='If true, repeats every week on the selected day')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Used when is_recurring is True', null=True)),
                ('specific_date', models.DateField(blank=True, help_text='Used when is_recurring is False', null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='accounts.vetprofile')),
            ],
            options={
                'verbose_name_plural': 'Vet Availabilities',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
