# Generated by Django 5.1 on 2026-05-16 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_created_at_user_is_banned_and_more'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetavailability',
            name='end_date',
            field=models.DateField(blank=True, help_text='Recurring availability stops after this date. Leave blank for indefinite.', null=True),
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, help_text="Optional note e.g. 'National holiday', 'Personal leave'", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='accounts.vetprofile')),
            ],
            options={
                'verbose_name': 'Blocked Date',
                'ordering': ['date'],
                'unique_together': {('vet', 'date')},
            },
        ),
    ]
