# Generated by Django 5.1 on 2026-05-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_vetavailability_end_date_blockeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='True once the 30-minute reminder email has been sent'),
        ),
    ]
