# Generated by Django 5.1 on 2026-05-31 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_appointment_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='symptom_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_photos', to='consultations.appointment')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
