# Generated by Django 5.1 on 2026-06-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_appointmentphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('livestock', 'Livestock'), ('other', 'Other')], max_length=10),
        ),
    ]
