# Generated by Django 5.1 on 2026-06-06 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_alter_pet_species'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='Taka amount discounted from consultation fee'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='original_consultation_fee',
            field=models.PositiveIntegerField(blank=True, help_text='Consultation fee at time of booking before any discount', null=True),
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, default='', help_text='Internal admin note about this coupon', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 20 for 20%) or fixed amount in Taka', max_digits=8)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Optional cap — e.g. '20% off but maximum ৳100'", max_digits=8, null=True)),
                ('customer_type', models.CharField(choices=[('all', 'All Customers'), ('new', 'New Customers Only'), ('returning', 'Returning Customers Only')], default='all', max_length=10)),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Global usage cap — leave blank for unlimited', null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='How many times one user can use this code')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='consultations.couponcode'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.PositiveIntegerField(help_text='Actual Taka amount discounted')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='consultations.appointment')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='consultations.couponcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
