# Generated by Django 5.1 on 2026-06-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('nutrition', 'Nutrition & Diet'), ('preventive_care', 'Preventive Care'), ('emergencies', 'Emergencies'), ('behaviour', 'Behaviour & Training'), ('grooming', 'Grooming & Hygiene'), ('general_health', 'General Health'), ('species_care', 'Species-Specific Care')], db_index=True, default='general_health', max_length=30),
        ),
    ]
